import { Customer } from "./types";

export const mockCustomers: Customer[] = [
  {
    id: "CUST-001",
    name: "Anand Distributors Pvt Ltd",
    customerType: "Wholesale Dealer",
    distributorName: "Anand Logistics West",
    jdeCode: "JDE-8472910",
    state: "Maharashtra",
    segment: "Automotive Lubricants",
    subSegment: "Logistics & Fleet",
    salesRep: "Rajesh Kumar",
    salesArea: "West 1 (Mumbai)",
    address: "Plot 12, GIDC Industrial Estate, Thane West, Mumbai, 400604",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2025-091 - Monsoon Fleet Base",
    gstNumber: "27AAACA1234A1Z1"
  },
  {
    id: "CUST-002",
    name: "Metro Auto Spares",
    customerType: "Key Account",
    distributorName: "Metro Lubricant Distributors",
    jdeCode: "JDE-1029384",
    state: "Delhi NCR",
    segment: "Automotive Lubricants",
    subSegment: "Passenger Car Workshops",
    salesRep: "Amit Sharma",
    salesArea: "North 1 (Delhi)",
    address: "A-45, Okhla Industrial Area Phase II, New Delhi, 110020",
    previousWbc: "No",
    previousWbcOffer: "None",
    gstNumber: "07AAACM4567M2Z2"
  },
  {
    id: "CUST-003",
    name: "Karnataka Heavy Logistics",
    customerType: "Direct Key Account",
    distributorName: "Southern Lubricant Providers",
    jdeCode: "JDE-9876543",
    state: "Karnataka",
    segment: "Automotive Lubricants",
    subSegment: "Logistics & Fleet",
    salesRep: "Sanjay Rao",
    salesArea: "South 1 (Bengaluru)",
    address: "8th Mile, Tumkur Road, Peenya Industrial Area, Bengaluru, 560058",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2024-512 - Heavy Duty Gold Package",
    gstNumber: "29AAACK7890K3Z3"
  },
  {
    id: "CUST-004",
    name: "Precision Metals & Forge",
    customerType: "Direct Industrial Account",
    distributorName: "Apex Industrial Suppliers",
    jdeCode: "JDE-5463728",
    state: "Tamil Nadu",
    segment: "Industrial Oils",
    subSegment: "Metalworking Fluids",
    salesRep: "Karthik Raja",
    salesArea: "South 2 (Chennai)",
    address: "Plot 89, SIPCOT Industrial Park, Sriperumbudur, Chennai, 602105",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2025-115 - Industrial Neat Cut",
    gstNumber: "33AAACP1209P4Z4"
  },
  {
    id: "CUST-005",
    name: "Gujarat Engineering Works",
    customerType: "Industrial Distributor",
    distributorName: "Gujarat Oil Trading Corp",
    jdeCode: "JDE-8837462",
    state: "Gujarat",
    segment: "Industrial Oils",
    subSegment: "Hydraulic Systems",
    salesRep: "Vijay Patel",
    salesArea: "West 2 (Ahmedabad)",
    address: "Block C, GIDC Naroda, Ahmedabad, 382330",
    previousWbc: "No",
    previousWbcOffer: "None",
    gstNumber: "24AAACG3456G5Z5"
  },
  {
    id: "CUST-006",
    name: "Yadav Transports & Co",
    customerType: "Direct Key Account",
    distributorName: "North India Lubrication Co",
    jdeCode: "JDE-7736452",
    state: "Uttar Pradesh",
    segment: "Automotive Lubricants",
    subSegment: "Logistics & Fleet",
    salesRep: "Ramesh Yadav",
    salesArea: "North 2 (Lucknow)",
    address: "Transport Nagar, Kanpur Road, Lucknow, 226012",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2025-021 - UP Logistics Support",
    gstNumber: "09AAACY7736Y6Z6"
  },
  {
    id: "CUST-007",
    name: "Royal Motors Workshop",
    customerType: "Workshop Partner",
    distributorName: "Western Auto Spares & Oils",
    jdeCode: "JDE-1192837",
    state: "Maharashtra",
    segment: "Automotive Lubricants",
    subSegment: "Passenger Car Workshops",
    salesRep: "Rajesh Kumar",
    salesArea: "West 1 (Mumbai)",
    address: "Senapati Bapat Marg, Lower Parel, Mumbai, 400013",
    previousWbc: "No",
    previousWbcOffer: "None",
    gstNumber: "27AAACR1192R7Z7"
  },
  {
    id: "CUST-008",
    name: "Hindustan Shipping Services",
    customerType: "Direct Key Account",
    distributorName: "East Coast Distribution Services",
    jdeCode: "JDE-4433221",
    state: "West Bengal",
    segment: "Marine & Energy",
    subSegment: "Coastal Shipping",
    salesRep: "Joydeep Basu",
    salesArea: "East 1 (Kolkata)",
    address: "4, Circular Garden Reach Road, Kidderpore, Kolkata, 700043",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2024-884 - Marine Cylinder Special",
    gstNumber: "19AAACH4433H8Z8"
  },
  {
    id: "CUST-009",
    name: "Telangana Power & Infrastructure",
    customerType: "Direct Industrial Account",
    distributorName: "Central Power & Industrial Oils",
    jdeCode: "JDE-9988776",
    state: "Telangana",
    segment: "Marine & Energy",
    subSegment: "Offshore Power Generation",
    salesRep: "Venkatesh Rao",
    salesArea: "South 3 (Hyderabad)",
    address: "Industrial Development Area, Jeedimetla, Hyderabad, 500055",
    previousWbc: "No",
    previousWbcOffer: "None",
    gstNumber: "36AAACT9988T9Z9"
  },
  {
    id: "CUST-010",
    name: "Rajasthan Marble cutting unit",
    customerType: "Direct Key Account",
    distributorName: "Deccan Lubricant Distributors",
    jdeCode: "JDE-5566778",
    state: "Rajasthan",
    segment: "Industrial Oils",
    subSegment: "Hydraulic Systems",
    salesRep: "Vikram Singh",
    salesArea: "North 3 (Jaipur)",
    address: "RIICO Industrial Area Phase IV, Udaipur, 313001",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2025-412 - Stone Cutting Hydraulic Discount",
    gstNumber: "08AAACR5566R0ZA"
  },
  {
    id: "CUST-011",
    name: "Speedway Motors",
    customerType: "Workshop Partner",
    distributorName: "Southern Lubricant Providers",
    jdeCode: "JDE-3344556",
    state: "Karnataka",
    segment: "Automotive Lubricants",
    subSegment: "Two-Wheeler Dealers",
    salesRep: "Sanjay Rao",
    salesArea: "South 1 (Bengaluru)",
    address: "Hosur Road, Wilson Garden, Bengaluru, 560027",
    previousWbc: "No",
    previousWbcOffer: "None",
    gstNumber: "29AAACS3344S1ZB"
  },
  {
    id: "CUST-012",
    name: "Ganga Paper Mills Ltd",
    customerType: "Direct Industrial Account",
    distributorName: "North India Lubrication Co",
    jdeCode: "JDE-6677889",
    state: "Uttar Pradesh",
    segment: "Industrial Oils",
    subSegment: "Gear & Bearing Lubrication",
    salesRep: "Ramesh Yadav",
    salesArea: "North 2 (Lucknow)",
    address: "Industrial Area, Naini, Prayagraj, 211008",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2025-103 - High Temp Bearing Pack",
    gstNumber: "09AAACG6677G2ZC"
  },
  {
    id: "CUST-013",
    name: "Balaji Auto Sales",
    customerType: "Wholesale Dealer",
    distributorName: "Gujarat Oil Trading Corp",
    jdeCode: "JDE-1212343",
    state: "Gujarat",
    segment: "Automotive Lubricants",
    subSegment: "Two-Wheeler Dealers",
    salesRep: "Vijay Patel",
    salesArea: "West 2 (Ahmedabad)",
    address: "Opposite RTO, Ring Road, Surat, 395001",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2024-009 - Dealer Incentive Program",
    gstNumber: "24AAACB1212B3ZD"
  },
  {
    id: "CUST-014",
    name: "Apex Logistics India",
    customerType: "Direct Key Account",
    distributorName: "Apex Industrial Suppliers",
    jdeCode: "JDE-7878909",
    state: "Tamil Nadu",
    segment: "Automotive Lubricants",
    subSegment: "Logistics & Fleet",
    salesRep: "Karthik Raja",
    salesArea: "South 2 (Chennai)",
    address: "Grand Southern Trunk Rd, Tambaram, Chennai, 600045",
    previousWbc: "No",
    previousWbcOffer: "None",
    gstNumber: "33AAACA7878A4ZE"
  },
  {
    id: "CUST-015",
    name: "Dynamic Metal Forging",
    customerType: "Key Account",
    distributorName: "Metro Lubricant Distributors",
    jdeCode: "JDE-3434567",
    state: "Haryana",
    segment: "Industrial Oils",
    subSegment: "Metalworking Fluids",
    salesRep: "Amit Sharma",
    salesArea: "North 1 (Delhi)",
    address: "Sector 25, IMT Manesar, Gurugram, 122050",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2025-707 - Forge Rebate Program",
    gstNumber: "06AAACD3434D5ZF"
  },
  {
    id: "CUST-016",
    name: "Coastal Wind Farm Ltd",
    customerType: "Direct Industrial Account",
    distributorName: "East Coast Distribution Services",
    jdeCode: "JDE-5656789",
    state: "West Bengal",
    segment: "Marine & Energy",
    subSegment: "Deep-Sea Vessel Maintenance",
    salesRep: "Joydeep Basu",
    salesArea: "East 1 (Kolkata)",
    address: "Salt Lake Sector V, Kolkata, 700091",
    previousWbc: "No",
    previousWbcOffer: "None",
    gstNumber: "19AAACC5656C6ZG"
  },
  {
    id: "CUST-017",
    name: "Mumbai Port Logistics",
    customerType: "Direct Key Account",
    distributorName: "Anand Logistics West",
    jdeCode: "JDE-2323456",
    state: "Maharashtra",
    segment: "Marine & Energy",
    subSegment: "Coastal Shipping",
    salesRep: "Rajesh Kumar",
    salesArea: "West 1 (Mumbai)",
    address: "P.D'Mello Road, Carnac Bunder, Mumbai, 400001",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2025-802 - Harbour Engine Rebates",
    gstNumber: "27AAACM2323M7ZH"
  },
  {
    id: "CUST-018",
    name: "Shree Krishna Oil & Lubricants",
    customerType: "Wholesale Dealer",
    distributorName: "Deccan Lubricant Distributors",
    jdeCode: "JDE-9090121",
    state: "Rajasthan",
    segment: "Specialty Lubricants",
    subSegment: "High-Temperature Grease",
    salesRep: "Vikram Singh",
    salesArea: "North 3 (Jaipur)",
    address: "Vishwakarma Industrial Area, Road No 14, Jaipur, 302013",
    previousWbc: "No",
    previousWbcOffer: "None",
    gstNumber: "08AAACS9090S8ZI"
  },
  {
    id: "CUST-019",
    name: "Bangalore Food Processing",
    customerType: "Key Account",
    distributorName: "Southern Lubricant Providers",
    jdeCode: "JDE-8181232",
    state: "Karnataka",
    segment: "Specialty Lubricants",
    subSegment: "Food-Grade Lubricants",
    salesRep: "Sanjay Rao",
    salesArea: "South 1 (Bengaluru)",
    address: "Whitefield Industrial Area, Bengaluru, 560066",
    previousWbc: "Yes",
    previousWbcOffer: "WBC-2025-303 - Food Grade Special",
    gstNumber: "29AAACB8181B9ZJ"
  },
  {
    id: "CUST-020",
    name: "Pharma Labs Special Co",
    customerType: "Key Account",
    distributorName: "Central Power & Industrial Oils",
    jdeCode: "JDE-7272838",
    state: "Telangana",
    segment: "Specialty Lubricants",
    subSegment: "Food-Grade Lubricants",
    salesRep: "Venkatesh Rao",
    salesArea: "South 3 (Hyderabad)",
    address: "Genome Valley, Shamirpet, Hyderabad, 500078",
    previousWbc: "No",
    previousWbcOffer: "None",
    gstNumber: "36AAACP7272P0ZK"
  }
];
