import { Sku } from "./types";

export const mockSkus: Sku[] = [
  {
    skuCode: "SKU-8392",
    skuName: "EDGE 5W-40 Synthetic",
    skuDataOption: "Synthetic",
    cogs: 420,
    lbmName: "LBM - High Performance",
    pvName: "HD",
    recMixIncentive: 2.2,
    mixIncentive: 2.2,
    skuRebate: 3.5,
    productTargetIncentive: 1.5
  },
  {
    skuCode: "SKU-4829",
    skuName: "GTX 15W-40 Mineral",
    skuDataOption: "Mineral",
    cogs: 280,
    lbmName: "LBM - Standard",
    pvName: "ILS",
    recMixIncentive: 1.5,
    mixIncentive: 1.5,
    skuRebate: 2.2,
    productTargetIncentive: 1.0
  },
  {
    skuCode: "SKU-9182",
    skuName: "CRB Turbo 15W-40 Diesel",
    skuDataOption: "Semi-Synthetic",
    cogs: 310,
    lbmName: "LBM - Light Duty",
    pvName: "FWS",
    recMixIncentive: 1.8,
    mixIncentive: 1.8,
    skuRebate: 2.5,
    productTargetIncentive: 1.2
  },
  {
    skuCode: "SKU-1001",
    skuName: "Magnatec 5W-30 SUV Synthetic",
    skuDataOption: "Synthetic",
    cogs: 440,
    lbmName: "LBM - SUV Special",
    pvName: "HD",
    recMixIncentive: 2.5,
    mixIncentive: 2.5,
    skuRebate: 4.0,
    productTargetIncentive: 2.0
  },
  {
    skuCode: "SKU-1002",
    skuName: "Activ 4T 10W-30 Semi-Synth",
    skuDataOption: "Semi-Synthetic",
    cogs: 199.62,
    lbmName: "LBM - 2W Premium",
    pvName: "MCO",
    recMixIncentive: 212.7259,
    mixIncentive: 1.0,
    skuRebate: 2.0,
    productTargetIncentive: 1.0,
    baseTO: 419.9153,
    baseCOGS: 199.62
  },
  {
    skuCode: "SKU-1003",
    skuName: "CRB Multi 20W-40 Mineral",
    skuDataOption: "Mineral",
    cogs: 250,
    lbmName: "LBM - Multi Fleet",
    pvName: "HD",
    recMixIncentive: 1.0,
    mixIncentive: 1.0,
    skuRebate: 2.0,
    productTargetIncentive: 0.9
  },
  {
    skuCode: "SKU-1004",
    skuName: "Hyspin AHM 46 Hydraulic",
    skuDataOption: "Mineral",
    cogs: 190,
    lbmName: "LBM - Hydraulic Standard",
    pvName: "IND",
    recMixIncentive: 0.8,
    mixIncentive: 0.8,
    skuRebate: 1.5,
    productTargetIncentive: 0.7
  },
  {
    skuCode: "SKU-1005",
    skuName: "Optigear Synthetic RO 150",
    skuDataOption: "Synthetic",
    cogs: 820,
    lbmName: "LBM - Heavy Gear Special",
    pvName: "IND",
    recMixIncentive: 5.0,
    mixIncentive: 5.0,
    skuRebate: 8.5,
    productTargetIncentive: 4.0
  },
  {
    skuCode: "SKU-1006",
    skuName: "Tribol GR 100-2 PD Grease",
    skuDataOption: "Synthetic",
    cogs: 750,
    lbmName: "LBM - High Temp Grease",
    pvName: "IND",
    recMixIncentive: 4.5,
    mixIncentive: 4.5,
    skuRebate: 7.0,
    productTargetIncentive: 3.5
  },
  {
    skuCode: "SKU-1007",
    skuName: "Spheerol EPL 2 Grease",
    skuDataOption: "Mineral",
    cogs: 220,
    lbmName: "LBM - EP Grease",
    pvName: "IND",
    recMixIncentive: 1.1,
    mixIncentive: 1.1,
    skuRebate: 2.0,
    productTargetIncentive: 0.8
  },
  {
    skuCode: "SKU-1008",
    skuName: "Iloform PN 226 Neat Draw",
    skuDataOption: "Mineral",
    cogs: 340,
    lbmName: "LBM - Drawing Fluid",
    pvName: "IND",
    recMixIncentive: 2.0,
    mixIncentive: 2.0,
    skuRebate: 3.2,
    productTargetIncentive: 1.5
  },
  {
    skuCode: "SKU-1009",
    skuName: "Cyltech 70 Marine Cylinder",
    skuDataOption: "Mineral",
    cogs: 510,
    lbmName: "LBM - Marine Heavy Duty",
    pvName: "MAR",
    recMixIncentive: 3.0,
    mixIncentive: 3.0,
    skuRebate: 5.0,
    productTargetIncentive: 2.5
  },
  {
    skuCode: "SKU-1010",
    skuName: "TLX Plus 30 Marine Engine",
    skuDataOption: "Semi-Synthetic",
    cogs: 480,
    lbmName: "LBM - Marine Auxiliary",
    pvName: "MAR",
    recMixIncentive: 2.8,
    mixIncentive: 2.8,
    skuRebate: 4.5,
    productTargetIncentive: 2.2
  },
  {
    skuCode: "SKU-1011",
    skuName: "Aircol PD 100 Compressor",
    skuDataOption: "Mineral",
    cogs: 390,
    lbmName: "LBM - Compressor Oil",
    pvName: "IND",
    recMixIncentive: 1.9,
    mixIncentive: 1.9,
    skuRebate: 3.0,
    productTargetIncentive: 1.2
  },
  {
    skuCode: "SKU-1012",
    skuName: "Perfecto HT 5 Heat Transfer",
    skuDataOption: "Mineral",
    cogs: 290,
    lbmName: "LBM - Thermal Fluid",
    pvName: "IND",
    recMixIncentive: 1.3,
    mixIncentive: 1.3,
    skuRebate: 2.5,
    productTargetIncentive: 1.0
  },
  {
    skuCode: "SKU-1013",
    skuName: "Anvol PE 46 XC Fire Resistant",
    skuDataOption: "Synthetic",
    cogs: 1150,
    lbmName: "LBM - Fire Safe Hyd",
    pvName: "IND",
    recMixIncentive: 8.0,
    mixIncentive: 8.0,
    skuRebate: 12.0,
    productTargetIncentive: 5.0
  },
  {
    skuCode: "SKU-1014",
    skuName: "Syntrans 75W-85 Gearbox",
    skuDataOption: "Synthetic",
    cogs: 610,
    lbmName: "LBM - Synthetic Gear",
    pvName: "HD",
    recMixIncentive: 3.5,
    mixIncentive: 3.5,
    skuRebate: 6.0,
    productTargetIncentive: 3.0
  },
  {
    skuCode: "SKU-1015",
    skuName: "Axle GL-5 80W-90 Gear Oil",
    skuDataOption: "Mineral",
    cogs: 270,
    lbmName: "LBM - Standard Gear",
    pvName: "HD",
    recMixIncentive: 1.2,
    mixIncentive: 1.2,
    skuRebate: 2.2,
    productTargetIncentive: 0.9
  },
  {
    skuCode: "SKU-1016",
    skuName: "Transmax ATF DEX III Multivehicle",
    skuDataOption: "Mineral",
    cogs: 320,
    lbmName: "LBM - Transmission Fluid",
    pvName: "HD",
    recMixIncentive: 1.6,
    mixIncentive: 1.6,
    skuRebate: 2.6,
    productTargetIncentive: 1.1
  },
  {
    skuCode: "SKU-1017",
    skuName: "EDGE 0W-20 Ultra Synthetic",
    skuDataOption: "Synthetic",
    cogs: 520,
    lbmName: "LBM - Ultra Perf SUV",
    pvName: "HD",
    recMixIncentive: 3.2,
    mixIncentive: 3.2,
    skuRebate: 5.0,
    productTargetIncentive: 2.5
  },
  {
    skuCode: "SKU-1018",
    skuName: "GTX Essential 20W-50 Petrol",
    skuDataOption: "Mineral",
    cogs: 240,
    lbmName: "LBM - Core Petrol",
    pvName: "ILS",
    recMixIncentive: 0.9,
    mixIncentive: 0.9,
    skuRebate: 1.8,
    productTargetIncentive: 0.8
  },
  {
    skuCode: "SKU-1019",
    skuName: "CRB Multi 15W-40 CI-4 Diesel",
    skuDataOption: "Mineral",
    cogs: 275,
    lbmName: "LBM - Commercial Diesel",
    pvName: "FWS",
    recMixIncentive: 1.3,
    mixIncentive: 1.3,
    skuRebate: 2.4,
    productTargetIncentive: 1.0
  },
  {
    skuCode: "SKU-1020",
    skuName: "Vecton 15W-40 CK-4 Heavy Duty",
    skuDataOption: "Semi-Synthetic",
    cogs: 350,
    lbmName: "LBM - High Performance HD",
    pvName: "FWS",
    recMixIncentive: 2.0,
    mixIncentive: 2.0,
    skuRebate: 3.0,
    productTargetIncentive: 1.4
  },
  {
    skuCode: "SKU-1021",
    skuName: "Vecton Fuel Saver 10W-30 Synth",
    skuDataOption: "Synthetic",
    cogs: 490,
    lbmName: "LBM - Premium Fleet HD",
    pvName: "FWS",
    recMixIncentive: 3.0,
    mixIncentive: 3.0,
    skuRebate: 4.8,
    productTargetIncentive: 2.0
  },
  {
    skuCode: "SKU-1022",
    skuName: "Activ Cruise 20W-50 4T Bike",
    skuDataOption: "Mineral",
    cogs: 195,
    lbmName: "LBM - 2W Cruiser",
    pvName: "MCO",
    recMixIncentive: 0.8,
    mixIncentive: 0.8,
    skuRebate: 1.5,
    productTargetIncentive: 0.6
  },
  {
    skuCode: "SKU-1023",
    skuName: "Power1 Ultimate 10W-40 Synth 4T",
    skuDataOption: "Synthetic",
    cogs: 380,
    lbmName: "LBM - 2W Racing Ultimate",
    pvName: "MCO",
    recMixIncentive: 2.2,
    mixIncentive: 2.2,
    skuRebate: 3.2,
    productTargetIncentive: 1.5
  },
  {
    skuCode: "SKU-1024",
    skuName: "Hyspin Spindle Oil 2",
    skuDataOption: "Mineral",
    cogs: 215,
    lbmName: "LBM - Spindle Fluid",
    pvName: "IND",
    recMixIncentive: 0.9,
    mixIncentive: 0.9,
    skuRebate: 1.6,
    productTargetIncentive: 0.8
  },
  {
    skuCode: "SKU-1025",
    skuName: "Rustilo DWX 30 Rust Prevent",
    skuDataOption: "Mineral",
    cogs: 280,
    lbmName: "LBM - Corrosion Control",
    pvName: "IND",
    recMixIncentive: 1.4,
    mixIncentive: 1.4,
    skuRebate: 2.2,
    productTargetIncentive: 1.0
  },
  {
    skuCode: "SKU-1026",
    skuName: "Magna GC 32 Guideway Lubricant",
    skuDataOption: "Mineral",
    cogs: 260,
    lbmName: "LBM - Slide Way Oil",
    pvName: "IND",
    recMixIncentive: 1.2,
    mixIncentive: 1.2,
    skuRebate: 2.1,
    productTargetIncentive: 0.9
  },
  {
    skuCode: "SKU-1027",
    skuName: "Molub-Alloy Paste TA Thread",
    skuDataOption: "Synthetic",
    cogs: 980,
    lbmName: "LBM - Extreme AntiSeize",
    pvName: "IND",
    recMixIncentive: 6.0,
    mixIncentive: 6.0,
    skuRebate: 9.5,
    productTargetIncentive: 4.5
  },
  {
    skuCode: "SKU-1028",
    skuName: "Viscogen KL 23 Chain Lubricant",
    skuDataOption: "Synthetic",
    cogs: 1050,
    lbmName: "LBM - High Temp Chain Oil",
    pvName: "IND",
    recMixIncentive: 7.0,
    mixIncentive: 7.0,
    skuRebate: 11.0,
    productTargetIncentive: 4.8
  },
  {
    skuCode: "SKU-1029",
    skuName: "Carix Synthetic Gas Engine Oil",
    skuDataOption: "Synthetic",
    cogs: 630,
    lbmName: "LBM - Gas Power Gen",
    pvName: "IND",
    recMixIncentive: 4.0,
    mixIncentive: 4.0,
    skuRebate: 6.5,
    productTargetIncentive: 2.8
  },
  {
    skuCode: "SKU-1030",
    skuName: "Tribol GR 4020 Grease",
    skuDataOption: "Semi-Synthetic",
    cogs: 420,
    lbmName: "LBM - Heavy Duty Grease",
    pvName: "IND",
    recMixIncentive: 2.2,
    mixIncentive: 2.2,
    skuRebate: 3.8,
    productTargetIncentive: 1.6
  },
  {
    skuCode: "SKU-1031",
    skuName: "Alusol SL 51 XF Soluble Metal",
    skuDataOption: "Semi-Synthetic",
    cogs: 450,
    lbmName: "LBM - Soluble Metal Cut",
    pvName: "IND",
    recMixIncentive: 2.5,
    mixIncentive: 2.5,
    skuRebate: 4.0,
    productTargetIncentive: 1.8
  },
  {
    skuCode: "SKU-1032",
    skuName: "Hyspin AWS 32 Hydraulic",
    skuDataOption: "Mineral",
    cogs: 195,
    lbmName: "LBM - Standard AWS 32",
    pvName: "IND",
    recMixIncentive: 0.8,
    mixIncentive: 0.8,
    skuRebate: 1.5,
    productTargetIncentive: 0.7
  },
  {
    skuCode: "SKU-1033",
    skuName: "Hyspin AWS 68 Hydraulic",
    skuDataOption: "Mineral",
    cogs: 205,
    lbmName: "LBM - Standard AWS 68",
    pvName: "IND",
    recMixIncentive: 0.8,
    mixIncentive: 0.8,
    skuRebate: 1.5,
    productTargetIncentive: 0.7
  },
  {
    skuCode: "SKU-1034",
    skuName: "Perfecto T 46 Turbine Oil",
    skuDataOption: "Mineral",
    cogs: 315,
    lbmName: "LBM - Standard Turbine",
    pvName: "IND",
    recMixIncentive: 1.4,
    mixIncentive: 1.4,
    skuRebate: 2.5,
    productTargetIncentive: 1.1
  },
  {
    skuCode: "SKU-1035",
    skuName: "Optigear BM 220 Industrial Gear",
    skuDataOption: "Mineral",
    cogs: 395,
    lbmName: "LBM - Ind Gear Extreme Load",
    pvName: "IND",
    recMixIncentive: 2.0,
    mixIncentive: 2.0,
    skuRebate: 3.5,
    productTargetIncentive: 1.5
  },
  {
    skuCode: "SKU-1036",
    skuName: "Spheerol AP 3 General Grease",
    skuDataOption: "Mineral",
    cogs: 180,
    lbmName: "LBM - General AP 3 Grease",
    pvName: "IND",
    recMixIncentive: 0.7,
    mixIncentive: 0.7,
    skuRebate: 1.2,
    productTargetIncentive: 0.5
  },
  {
    skuCode: "SKU-1037",
    skuName: "TLX Xtra 40 Heavy Marine Aux",
    skuDataOption: "Mineral",
    cogs: 460,
    lbmName: "LBM - Marine Aux Heavy",
    pvName: "MAR",
    recMixIncentive: 2.5,
    mixIncentive: 2.5,
    skuRebate: 4.2,
    productTargetIncentive: 1.8
  },
  {
    skuCode: "SKU-1038",
    skuName: "BioTrans 46 Environment Hydraulic",
    skuDataOption: "Synthetic",
    cogs: 720,
    lbmName: "LBM - Biodegradable Hyd",
    pvName: "IND",
    recMixIncentive: 4.0,
    mixIncentive: 4.0,
    skuRebate: 6.8,
    productTargetIncentive: 3.0
  },
  {
    skuCode: "SKU-1039",
    skuName: "Optileb GT 220 Food Grade Gear",
    skuDataOption: "Synthetic",
    cogs: 860,
    lbmName: "LBM - Food Grade Gear",
    pvName: "IND",
    recMixIncentive: 5.2,
    mixIncentive: 5.2,
    skuRebate: 8.8,
    productTargetIncentive: 3.8
  },
  {
    skuCode: "SKU-1040",
    skuName: "Braycote 601EF Space Grease",
    skuDataOption: "Synthetic",
    cogs: 4200,
    lbmName: "LBM - Ultra High Vacuum",
    pvName: "IND",
    recMixIncentive: 25.0,
    mixIncentive: 25.0,
    skuRebate: 40.0,
    productTargetIncentive: 18.0
  }
];
