import { PipelineOffer } from "./types";

export const mockOffers: PipelineOffer[] = [
  // Draft
  {
    offerCode: "WBC-WS-587",
    customerName: "SAGAR AUTO SERVECE , VITA",
    customerBadges: ["DIRECT", "Existing Customer"],
    segment: "Automotive Lubricants",
    wbcPeriod: { startMonth: "Aug 2026", durationMonths: 12, endMonth: "Jul 2027" },
    committedVol: 10000,
    totalInvestment: 80000,
    avgGmpl: 125.4,
    dofaApproval: "Area Sales Manager",
    status: "Draft",
  },
  {
    offerCode: "WBC-WS-1399",
    customerName: "Frontier Bajaj",
    customerBadges: ["DISTRIBUTOR", "Existing Customer"],
    segment: "Automotive Lubricants",
    wbcPeriod: { startMonth: "Sep 2026", durationMonths: 24, endMonth: "Aug 2028" },
    committedVol: 24000,
    totalInvestment: 150000,
    avgGmpl: 142.1,
    dofaApproval: "Territory Manager",
    status: "Draft",
  },
  {
    offerCode: "WBC-WS-2055",
    customerName: "SAI SERVICE STATION",
    customerBadges: ["DIRECT", "New Customer"],
    segment: "Motorcycle Oils",
    wbcPeriod: { startMonth: "Oct 2026", durationMonths: 12, endMonth: "Sep 2027" },
    committedVol: 8000,
    totalInvestment: 50000,
    avgGmpl: 110.5,
    dofaApproval: "Area Sales Manager",
    status: "Draft",
  },
  // Pending Approval
  {
    offerCode: "WBC-WS-13652",
    customerName: "Test 1",
    customerBadges: ["DIRECT", "New Customer"],
    segment: "Automotive Lubricants",
    wbcPeriod: { startMonth: "Jun 2026", durationMonths: 36, endMonth: "May 2029" },
    committedVol: 45000,
    totalInvestment: 250000,
    avgGmpl: 135.8,
    dofaApproval: "Sales Director (L4)",
    status: "Pending Approval",
  },
  {
    offerCode: "WBC-WS-1471",
    customerName: "POPULAR MEGA MOTORS",
    customerBadges: ["DISTRIBUTOR", "Existing Customer"],
    segment: "Industrial Oils",
    wbcPeriod: { startMonth: "Jul 2026", durationMonths: 12, endMonth: "Jun 2027" },
    committedVol: 180000,
    totalInvestment: 850000,
    avgGmpl: 98.4,
    dofaApproval: "Managing Director (L6)",
    status: "Pending Approval",
  },
  {
    offerCode: "WBC-WS-18156",
    customerName: "Test 01st June 2026",
    customerBadges: ["DIRECT", "Existing Customer"],
    segment: "Automotive Lubricants",
    wbcPeriod: { startMonth: "Jun 2026", durationMonths: 12, endMonth: "May 2027" },
    committedVol: 5000,
    totalInvestment: 20000,
    avgGmpl: 118.2,
    dofaApproval: "Territory Manager (L1)",
    status: "Pending Approval",
  },
  {
    offerCode: "WBC-WS-18238",
    customerName: "AB MOTORS",
    customerBadges: ["DIRECT", "Existing Customer"],
    segment: "Automotive Lubricants",
    wbcPeriod: { startMonth: "Aug 2026", durationMonths: 24, endMonth: "Jul 2028" },
    committedVol: 60000,
    totalInvestment: 400000,
    avgGmpl: 128.5,
    dofaApproval: "VP Sales (L3)",
    status: "Pending Approval",
  },
  // Published
  {
    offerCode: "WBC-WS-3843",
    customerName: "ASHOK LEYLAND",
    customerBadges: ["DIRECT", "Existing Customer"],
    segment: "Commercial Vehicle Oils",
    wbcPeriod: { startMonth: "May 2026", durationMonths: 12, endMonth: "Apr 2027" },
    committedVol: 120000,
    totalInvestment: 600000,
    avgGmpl: 130.2,
    dofaApproval: "Territory Manager (L1)",
    status: "Published",
  },
  {
    offerCode: "WBC-WS-5960",
    customerName: "ABT LIMITED",
    customerBadges: ["DISTRIBUTOR", "Existing Customer"],
    segment: "Automotive Lubricants",
    wbcPeriod: { startMonth: "Feb 2026", durationMonths: 24, endMonth: "Jan 2028" },
    committedVol: 50000,
    totalInvestment: 350000,
    avgGmpl: 115.4,
    dofaApproval: "Territory Manager (L1)",
    status: "Published",
  },
  // Closed
  {
    offerCode: "WBC-WS-11874",
    customerName: "Test FWS DS",
    customerBadges: ["DIRECT", "Existing Customer"],
    segment: "Automotive Lubricants",
    wbcPeriod: { startMonth: "Aug 2025", durationMonths: 12, endMonth: "Jul 2026" },
    committedVol: 15000,
    totalInvestment: 75000,
    avgGmpl: 122.9,
    dofaApproval: "Territory Manager (L1)",
    status: "Closed / Closure",
  },
  // Cancelled
  {
    offerCode: "WBC-WS-993",
    customerName: "test usd new",
    customerBadges: ["DIRECT", "New Customer"],
    segment: "Automotive Lubricants",
    wbcPeriod: { startMonth: "Apr 2026", durationMonths: 12, endMonth: "Mar 2027" },
    committedVol: 10000,
    totalInvestment: 90000,
    avgGmpl: 88.6,
    dofaApproval: "Sales Director (L4)",
    status: "Cancelled",
  },
];
